using Common.Tests.Base;
using Common.Tests;
using Common.Tests.WebElements;
using OpenQA.Selenium;

namespace Common.Tests.Pages.Accounts {
    public class AutoGeneratedPage : BPMInternalBasePage {
        public AutoGeneratedPage(IWebDriver driver) : base(driver) {

        }
        public WebElement CancelButton {
            get {
                return TryGetElement(By.Id("AutoGeneratedPageV2CancelButtonButton-textEl"));
            }
        }
        public void Close() {

        }
    }
}